### ISSUE TITLE
Child img element with no alt-attribute

### ISSUE THREAD

**Issue by derjohnschmidt** [datocms/react-datocms#10]
Hey there!

I'm using `react-datocms^1.2.4` currently on my Next.js `next^9.4.0` application. I've noticed, that the `Image` component renders a transparent `img` element within the parent `div` element:
```
  <img
    style="display: block; width: 100%;"
    src="data:image/svg+xml;base64..."
  />
``` 
What I'm missing is an decorative `alt` attribute or an option to customize hence it disturbs the accessibility of the page. Is there any way to fix this on my side?

**Comment by stefanoverna** [comment]
Not at the moment.. what would be the correct way to handle this image from an A11y point of view?

—
Stefano Verna

DatoCMS

--- original message ---
On May 18, 2020, 11:58 AM GMT+2 notifications@github.com wrote:



Hey there!

I'm using react-datocms^1.2.4 currently on my Next.js next^9.4.0 application. I've noticed, that the Image component renders a transparent img element within the parent div element:

<img
style="display: block; width: 100%;"
src="data:image/svg+xml;base64..."
/>

What I'm missing is an decorative alt attribute or an option to customize hence it disturbs the accessibility of the page. Is there any way to fix this on my side?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by derjohnschmidt** [comment]
Maybe this little tweak could help? #11

**Comment by jordykoppen** [comment]
An empty alt would still fail tests if you test for basic a11y. On top of that, it isn’t a screen reader friendly alternative either.

@stefanoverna what is the transparent img tag for?

**Comment by derjohnschmidt** [comment]
> An empty alt would still fail tests if you test for basic a11y. On top of that, it isn’t a screen reader friendly alternative either.
> 
> @stefanoverna what is the transparent img tag for?

Other than that I'd just have a `role="presentation"` attribute in terms of a11y in mind. Thoughts?

**Comment by stefanoverna** [comment]
The image is for properly size the real image before it actually loads. I'm OK with role=presentation, seems the best to me!

--- original message ---
On Mon, May 18 at 06:28 PM, <notifications@github.com> John Schmidt wrote:



> An empty alt would still fail tests if you test for basic a11y. On top of that, it isn’t a screen reader friendly alternative either.

> @stefanoverna what is the transparent img tag for?


Other than that I'd just have a role="presentation" attribute in terms of a11y in mind. Thoughts?

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
