### ISSUE TITLE
Add width and height to HTML img element to comply with Lighthouse speed test

### ISSUE THREAD

**Issue by thierry-rietsch** [datocms/react-datocms#22]
When using the Image element from react-datocms, the generated image tag does not contain a width and height. When running a Google Web.Dev measure, then the missing properties on the image tag lead to the issue "Image elements do not have explicit width and height". This is considered by Google as pretty suboptimal.

Would it be possible to add those attributes on the image tag, so the browser could already reserve the space to prevent content jumping around and page speed would be happy? Or is this something you consider as irrelevant and PageSpeed related only?

**Comment by stefanoverna** [comment]
Hey @thierry-rietsch, this is actually a false alarm from PageSpeed :) 

Instead of using explicit width/height on the image itself — which would prevent this component from working in fluid layouts where the image has to take the full width, we use a different method to pre-compute layout thrashing, which is to create an empty SVG image embedded in base64 (so immediately available) that takes the needed space :)

It's a superior approach both in terms of flexibility and developer experience (the component behaves exactly as a regular image), but I guess PageSpeed is not smart enough to understand it :) 

https://github.com/datocms/react-datocms/blob/master/src/Image/index.tsx#L177-L188

**Comment by thierry-rietsch** [comment]
Yeah, thought so that a fixed width and height is suboptimal. Thanks for the reply and keep up your great work!
