### ISSUE TITLE
Consider adding callback to Image load / shown events or styling

### ISSUE THREAD

**Issue by dbismut** [datocms/react-datocms#38]
Maybe this can be already achieved with the given API, but I'd like to apply a specific animation to an image when it's loaded and in view the first time. Currently, since it doesn't seem `Image` accepts ref forwarding, this means that one has to wrap the Image inside another `div`, which is a potential mess up when it comes to image position (and I'm not even sure this would suffice anyway).

**Comment by stefanoverna** [comment]
👍 Would you be able to work on a PR David? 

—
Stefano Verna
Founder and CEO @ DatoCMS

--- original message ---
On December 19, 2021 at 10:36 AM GMT+1 ***@***.*** wrote:



Maybe this can be already achieved with the given API, but I'd like to apply a specific animation to an image when it's loaded and in view the first time. Currently, since it doesn't seem Image accepts ref forwarding, this means that one has to wrap the Image inside another div, which is a potential mess up when it comes to image position.

—

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
--- end of original message ---

**Comment by dbismut** [comment]
Sure, as soon as I have some time off!

**Comment by dbismut** [comment]
@stefanoverna what's the best way to setup a dev environment with this repo?

**Comment by stefanoverna** [comment]
Hey @dbismut sorry for the delay. We've added some help here: https://github.com/datocms/react-datocms#development
Is that enough? :)

**Comment by dbismut** [comment]
That's great thanks :)

Would you be open to moving to a more modern repo architecture? I've had good results with `preconstruct`, and there's now `turborepo` that could also work.

You would spawn examples from a Vite server, every package is linked and watched effortlessly. You could also tie examples with codesandbox which would probably make it easier for you to manage PR. 

And finally I find `changeset` super useful when releasing packages. 

You can have a look at how I made it work here: https://github.com/pmndrs/use-gesture

No rocket science, but it's still some work, we can keep this for later if you're not comfortable with the process, just keep it in mind!

**Comment by stefanoverna** [comment]
Definitely open, the only fear is moving to some solution that will become old/unsupported too soon, so the more lightweight it's the tooling, the better :) I've heard good things about turborepo too!
