### ISSUE TITLE
Post transformed height in GraphQL doesn't match Imgix param maxW

### ISSUE THREAD

**Issue by dbismut** [datocms/react-datocms#62]
```gql
responsiveImage(imgixParams: { fit: crop, w: 720, h: 600, auto: format }) {
  width
  height
}
```

Returned height is 1079 when it should be max 600.

**Comment by stefanoverna** [comment]
Hey @dbismut.. just tried on a project, and seems to work:

![Screenshot 2022-09-28 at 12 08 42](https://user-images.githubusercontent.com/51573/192752571-949ed5cf-3ece-412d-bb74-be775964605f.png)

Maybe you can share some details about your specific project by sending a request [here](https://www.datocms.com/support?topics=technical-support/ive-found-a-bug)?

I'm closing the issue here, as it's not related to the `react-datocms` package in any case! :)

**Comment by dbismut** [comment]
Wasn't sure where to report this! But indeed looks like it's related to the api. I'll get back to you asap in this thread.

**Comment by dbismut** [comment]
@stefanoverna here is what is returned by Dato's API. Note that I'm talking about `max-h`, not `h` (and there I realize that I posted the wrong GraphQL request in the issue sorry, fixing this now).

```json
{
    "src": "https://www.datocms-assets.com/80841/1663424168-man-working-at-his-desk.jpg?auto=format&fit=crop&max-h=600&w=720",
    "width": 720,
    "height": 1079,
    "aspectRatio": 0.6669921875,
}
```

**Comment by dbismut** [comment]
Hey @stefanoverna did you have the time to look into this? Nothing especially urgent but just wondering if this is on track.

**Comment by stefanoverna** [comment]
Should be fixed now @dbismut! 👍🏼

**Comment by dbismut** [comment]
@stefanoverna Indeed! Thanks a lot :)
