### ISSUE TITLE
Styling placeholder

### ISSUE THREAD

**Issue by bebejane** [datocms/react-datocms#66]
I'm styling my image with pictureStyle prop, changing the size of the image. This causes problem with the placeholder not matching in size. Would it be possible to add a prop for styling placeholder image or maybe the picture style could be applied to the placeholder as well.

**Comment by stefanoverna** [comment]
Maybe it would be better to apply the pictureStyle prop also to the placeholder?

—
Stefano Verna
Founder and CEO @ DatoCMS

--- original message ---
On November 11, 2022 at 7:31 PM GMT+1 ***@***.*** wrote:



I'm styling my image with pictureStyle prop, changing the size of the image. This causes problem with the placeholder not matching in size. Would it be possible to add a prop for styling placeholder image or maybe the picture style could be applied to the placeholder as well.

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
--- end of original message ---

**Comment by bebejane** [comment]
Yes that would be the easiest solution but it might cause unwanted stying for others possibly. For my case it would work.

**Comment by stefanoverna** [comment]
Can I ask for the exact use case? What are you trying to achieve? How are you trying to change the size of the image? For that you should use the `layout` prop, or `style`.. 😕

**Comment by bebejane** [comment]
I'm changing styling of the image based on scroll position. Is there another way to do it?

**Comment by stefanoverna** [comment]
Relased placeholderStyle and placeholderClassName in v4.0.5! 👍🏼
