### ISSUE TITLE
Image Resize Bug 1.2.1 => 1.2.2

### ISSUE THREAD

**Issue by followbl** [datocms/react-datocms#9]
Hello - love datocms and have been really happy with how easy it has been to get started and setup. We have a pretty 1:1 setup w/ the example in the nextjs/examples dir, but upon upgrading from 1.2.1 => 1.2.2 something has gone wrong with our image-resizing.

I looked through the changelogs and commits logs with the latest and didn't see anything glaring. 

I've attached before and afters...since we have since rolled-back. Happy to provide any additional information or test it out locally.

Before
![after](https://user-images.githubusercontent.com/927065/81324671-4ca1f300-9065-11ea-94f4-ce111b546294.png)

After
![full-size](https://user-images.githubusercontent.com/927065/81324703-588db500-9065-11ea-914d-6b4ea53763f3.png)

**Comment by stefanoverna** [comment]
Hi! Any chance you can paste the snippet of the code you're using to generate one of the images, and pass us the resulting HTML+CSS of the page (File > Save page as... > Web page, complete)?

--- original message ---
On Thu, May 7 at 07:19 PM, <notifications@github.com> Brad Larson wrote:



Hello - love datocms and have been really happy with how easy it has been to get started and setup. We have a pretty 1:1 setup w/ the example in the nextjs/examples dir, but upon upgrading from 1.2.1 => 1.2.2 something has gone wrong with our image-resizing.

I looked through the changelogs and commits logs with the latest and didn't see anything glaring.

I've attached before and afters...since we have since rolled-back. Happy to provide any additional information or test it out locally.

Before


After


—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by followbl** [comment]
absolutely @stefanoverna 

```js
import cn from 'classnames';
import Link from 'next/link';
import { Image } from 'react-datocms';

interface CoverImageInterface {
  title: string;
  responsiveImage: any;
  slug?: string;
}

export function CoverImage({ title, responsiveImage, slug }: CoverImageInterface) {
  const image = (
    <Image
      data={{
        ...responsiveImage,
        alt: `Cover Image for ${title}`,
      }}
      className={cn('shadow-small rounded', {
        'hover:shadow-medium transition-shadow duration-200': slug,
      })}
    />
  );
  return (
    <div className="mx-0">
      {slug ? (
        <Link as={`/blog/posts/${slug}`} href="/blog/posts/[slug]">
          <a className={'h-auto w-auto'} aria-label={title}>
            {image}
          </a>
        </Link>
      ) : (
        image
      )}
    </div>
  );
}
```

Here's the fetch for the homepage

```js
export async function getAllPostsForHome(preview: any) {
  const data = await fetchAPI(
    `
    {
      allPosts(orderBy: date_DESC, first: 20) {
        title
        slug
        excerpt
        date
        content
        coverImage {
          responsiveImage(imgixParams: {fm: jpg, fit: crop, w: 1500, h: 1000 }) {
            ...responsiveImageFragment
          }
        }
        author {
          name
          picture {
            url(imgixParams: {fm: jpg, fit: crop, w: 100, h: 100, sat: -100})
          }
        }
        tags {
          name
        }
      }
    }
    ${responsiveImageFragment}
  `,
    { preview }
  );
  return data?.allPosts;
}
```

**Comment by stefanoverna** [comment]
@followbl could you please try with 1.2.4? should be solved now.. pretty hard to make placeholders work in universal mode, lazy loaded, correctly sized, and with IE11 support :)

**Comment by followbl** [comment]
I feel your pain - and I don't wish IE11 support on my worst enemy. 

Your fix works perfectly. Thank you, closing the issue 🚀
